### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by Airace99** [brightcone/bart_frontend#13]
Description:
Please use following while developing 
width: Fixed (360px)px;
height: Hug (459px)px;
top: 153px;
left: 854px;
gap: 32px;
opacity: 0px;

Add photo capture as part of sign up page as per current UI page

<img width="695" alt="Screenshot 2024-08-30 at 2 01 27 PM" src="https://github.com/user-attachments/assets/9da1ade9-da38-4068-b250-0d9460f7ec9b">

**Comment by tulaseerao** [comment]
@Airace99 Please attach screenshots and description

**Comment by Airace99** [comment]
Sure will do

**Comment by Airace99** [comment]
refer the below screen shot 
<img width="695" alt="Screenshot 2024-08-30 at 2 01 27 PM" src="https://github.com/user-attachments/assets/41c486c5-0713-47e5-a9c8-2bca1e798907">

**Comment by PBSquare** [comment]
I worked on Signup page and mostly completed this page, need to do some minor modifications to this page
