### ISSUE TITLE
Login_page

### ISSUE THREAD

**Issue by Airace99** [brightcone/bart_frontend#14]
Description:
For the login page use the below parameters
width: 739.02px;
height: 800.46px;
top: 9px;
left: 711px;
gap: 0px;
opacity: 0.2px;

<img width="715" alt="Screenshot 2024-08-30 at 2 01 52 PM" src="https://github.com/user-attachments/assets/7fbc81e8-77e5-420c-9ec6-51f174e463a1">

**Comment by PBSquare** [comment]
I am almost done with this Login Page, need to do small changes
